### ISSUE TITLE
New version of facepunch no longer need to copy steamAppId.txt

### ISSUE THREAD

**Issue by ScriptsEngineer** [Agoxandr/MirrorSteamNetworkingSockets#1]

**Comment by Agoxandr** [comment]
Im no longer working on this Forgot to archive. https://github.com/Agoxandr/Mirror-Steamworks/ is a fork of Mirror I made which I also no longer update, you could try.

Depending on how far you are away from release I would recommend using https://github.com/Unity-Technologies/com.unity.multiplayer.mlapi which releases Q1 2021. It will have breaking changes to the existing MLAPI which is superior to Mirror.

You have to maintain this yourself, sorry. If you have any questions you can ask me at any time.
